"""Update product model

Revision ID: 756d94213a13
Revises: d8a1867751ff
Create Date: 2022-12-17 20:19:46.505310

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '756d94213a13'
down_revision = 'd8a1867751ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price_stripe_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price_stripe_id')
    # ### end Alembic commands ###
