"""init

Revision ID: 4ba69b5fb2c0
Revises: 
Create Date: 2022-12-24 14:49:55.340580

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = '4ba69b5fb2c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_type', sa.String(length=128), nullable=False),
    sa.Column('product_stripe_id', sa.String(length=128), nullable=True),
    sa.Column('price_stripe_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'ERROR', 'CANCELED', name='orderstatus'), nullable=True),
    sa.Column('pay_intent_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', name='subscriptionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###

    op.execute("INSERT INTO product(id, name, product_type, product_stripe_id, "
               "price_stripe_id, description,duration,price,currency_code,recurring,is_active) VALUES "
               "('25b3c1fc-383a-4575-95dc-1542c60b9db6', 'Monthly', 'Subscription', 'prod_N2lNvWXDuh6USH', 'price_1MIfqjInWuMfFLjmfv7lC74G','Monthly sub for service', 1, 100,'rub', True, True),"
               "('8120c1e7-e8ee-495d-b3fe-8f2f10f661a5', 'Quarter', 'Subscription', 'prod_N2lOQj2k9b3otT', 'price_1MIfrHInWuMfFLjmyTsmoLdP','Quarter sub for service', 3, 240,'rub', True, True),"
               "('68b0cc8a-debf-425c-8d33-5ed009cde428', 'Half year', 'Subscription', 'prod_N2lOlVFiUm3WKY', 'price_1MIfrcInWuMfFLjmyEmxJY3N','Half year sub for service', 6, 360,'rub', True, True)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    op.drop_table('subscription')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
